### ISSUE TITLE
Couldn't follow symbolic link in Windows 7

### ISSUE THREAD

**Issue by koluch** [ddispaltro/sbt-reactjs#5]
Hi!

It seems, plugin couldn't follow NTFS symbolic links properly. I keep my project in folder "d:\koluch\dev\scala\test\", where "d:\koluch\dev" is symbolic link to another folder, and I get following error: 

```
play.PlayExceptions$UnexpectedException: Unexpected exception[JsTaskFailure: Wrapped java.security.AccessControlException: access denied ("java.io.FilePermission" "D:\koluch\dev" "readlink") (/Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js#695)      at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js:695 (anonymous)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js:1283 (realpathSync)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:142 (tryFile)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:181 (anonymous)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:336 (anonymous)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:280 (anonymous)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:497 (anonymous)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:141 (startup)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:872 (anonymous)
]
        at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:237) ~[na:na]
        at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
        at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
        at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
        at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
Caused by: com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: Wrapped java.security.AccessControlException: access denied ("java.io.FilePermission" "D:\koluch\dev" "readlink") (/Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js#695)  at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js:695 (anonymous)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js:1283 (realpathSync)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:142 (tryFile)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:181 (anonymous)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:336 (anonymous)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:280 (anonymous)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/module.js:497 (anonymous)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:141 (startup)
        at /Users/Apigee/src/noderunner/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:872 (anonymous)

        at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:195) ~[na:na]
        at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:167) ~[na:na]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206) ~[scala-library-2.11.1.jar:na]
        at scala.util.Try$.apply(Try.scala:161) ~[scala-library-2.11.1.jar:na]
        at scala.util.Success.map(Try.scala:206) ~[scala-library-2.11.1.jar:na]
```

When I am trying to run activator by real path of project, everything works properly. I am using 0.4.0 version of sbt-reactjs

**Comment by ddispaltro** [comment]
Any ideas how to fix this? I don't know windows well. Most of the file i/o is provided by sbt-web/sbt-jsengine projects...

**Comment by ddispaltro** [comment]
You could also try a different engine, this looks more like a https://github.com/typesafehub/js-engine issue.
